# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_streaming_pb2 as server__streaming__pb2


class ServerStreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamingFromServer = channel.unary_stream(
                '/server_streaming.ServerStreaming/StreamingFromServer',
                request_serializer=server__streaming__pb2.StreamingFromServerRequest.SerializeToString,
                response_deserializer=server__streaming__pb2.StreamingFromServerResponse.FromString,
                )


class ServerStreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamingFromServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamingFromServer': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamingFromServer,
                    request_deserializer=server__streaming__pb2.StreamingFromServerRequest.FromString,
                    response_serializer=server__streaming__pb2.StreamingFromServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_streaming.ServerStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerStreaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamingFromServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/server_streaming.ServerStreaming/StreamingFromServer',
            server__streaming__pb2.StreamingFromServerRequest.SerializeToString,
            server__streaming__pb2.StreamingFromServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
