# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_streaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16server_streaming.proto\x12\x10server_streaming\"/\n\x1aStreamingFromServerRequest\x12\x11\n\tnum_bytes\x18\x01 \x01(\x05\"+\n\x1bStreamingFromServerResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x87\x01\n\x0fServerStreaming\x12t\n\x13StreamingFromServer\x12,.server_streaming.StreamingFromServerRequest\x1a-.server_streaming.StreamingFromServerResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_streaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STREAMINGFROMSERVERREQUEST']._serialized_start=44
  _globals['_STREAMINGFROMSERVERREQUEST']._serialized_end=91
  _globals['_STREAMINGFROMSERVERRESPONSE']._serialized_start=93
  _globals['_STREAMINGFROMSERVERRESPONSE']._serialized_end=136
  _globals['_SERVERSTREAMING']._serialized_start=139
  _globals['_SERVERSTREAMING']._serialized_end=274
# @@protoc_insertion_point(module_scope)
